# Generated by Django 5.2.16 on 2026-07-23 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('followers', models.CharField(max_length=50)),
                ('year', models.IntegerField(default=2022)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.CharField(default='USA', max_length=50)),
                ('is_in_stock', models.BooleanField(default=True)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('icon_name', models.CharField(default='Instagram', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(blank=True, max_length=255)),
                ('target_link', models.CharField(max_length=500)),
                ('quantity', models.IntegerField(default=1000)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Processing', 'Processing'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Canceled', 'Canceled')], default='Pending', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('rate_per_1k', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_order', models.IntegerField(default=10)),
                ('max_order', models.IntegerField(default=100000)),
                ('description', models.TextField(blank=True)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal'), ('Order Payment', 'Order Payment'), ('Refund', 'Refund')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Completed', max_length=20)),
                ('method', models.CharField(default='Flutterwave', max_length=50)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
