# Generated by Django 5.2.16 on 2026-07-23 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_referral_supportticket_ticketreply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_url', models.URLField(help_text='Standard SMM Panel API v2 URL (e.g. https://provider.com/api/v2)')),
                ('api_key', models.CharField(max_length=255)),
                ('margin_percentage', models.DecimalField(decimal_places=2, default=30.0, help_text='Percentage markup added to provider prices', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='provider_order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='remains',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='start_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='service',
            name='provider_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='provider_service_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Completed', 'Completed'), ('Processing', 'Processing'), ('In Progress', 'In Progress'), ('Pending', 'Pending'), ('Failed', 'Failed'), ('Canceled', 'Canceled'), ('Partial', 'Partial')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='marketplace.provider'),
        ),
    ]
