# Generated by Django 5.2.16 on 2026-08-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Moniepoint / GTBank', max_length=100)),
                ('account_name', models.CharField(default='HopeSocial Ltd', max_length=100)),
                ('account_number', models.CharField(default='2034829102', max_length=50)),
                ('flutterwave_public_key', models.CharField(blank=True, default='FLWPUBK_TEST-demo-key', max_length=255)),
                ('flutterwave_secret_key', models.CharField(blank=True, default='', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
