# Generated by Django 5.2.16 on 2026-08-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_paymentsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountitem',
            name='stock_count',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='order',
            name='deliverable_info',
            field=models.TextField(blank=True, default='', help_text='Account credentials or download link delivered to buyer'),
        ),
        migrations.AddField(
            model_name='service',
            name='stock_count',
            field=models.IntegerField(default=1000),
        ),
    ]
