# Generated by Django 5.2.16 on 2026-08-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_accountitem_stock_count_order_deliverable_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountitem',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Login credentials, email, or account specs'),
        ),
    ]
